### ISSUE TITLE
[e2c9225] "Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style"

### ISSUE THREAD

**Issue by JaimeDeFi** [VenusProtocol/venus-protocol-interface#110]
Found an issue trying to build [e2c9225] with Docker on Windows.
Got a ton of errors: "Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style".

I have solved it adding the next on .eslintrc.js
'linebreak-style': 0,

Is there any other approach? Maybe through modifying dockerfile or .env ?

**Comment by coreyar** [comment]
For consistency we are going to keep the line break style linting rule. You can resolve this on windows by configuring your editor to use LF control character for line breaks
