### ISSUE TITLE
When will the app support "Wallet Connect" and "Ledger"?

### ISSUE THREAD

**Issue by JUSTISBEN** [VenusProtocol/venus-protocol-interface#12]
![图片](https://user-images.githubusercontent.com/85735717/139347739-659587cf-6b74-49cf-97e2-1031e1a77609.png)

**Comment by kkirka** [comment]
WalletConnect support has been released. Re: Ledger — you can use Metamask now to connect your Ledger. Do you think the direct support should be prioritized regardless?

**Comment by JUSTISBEN** [comment]
Thanks for that.

Having direct support will be more better, the users will not get confused during using.
