### ISSUE TITLE
Please lower the ranking of SXP in app

### ISSUE THREAD

**Issue by JUSTISBEN** [VenusProtocol/venus-protocol-interface#18]
![Screenshot 2021-11-14 at 22-00-38 Venus Protocol](https://user-images.githubusercontent.com/85735717/141684568-6f803e13-4390-4be1-a084-f763f1b15aeb.png)

![Screenshot 2021-11-14 at 22-00-47 Venus Protocol](https://user-images.githubusercontent.com/85735717/141684444-ff5cdaea-ce2a-4603-8e85-27bb99dc2ec8.png)
)

and this, and i think we didn't need the chart of APY, there have too many repeating data show in here and market module.

![Screenshot 2021-11-15 at 17-41-51 Venus Protocol](https://user-images.githubusercontent.com/85735717/141758932-6ba63e35-c6ce-4e44-b1cf-5ce5b77cba10.png)

Thanks

**Comment by coreyar** [comment]
We have released a new dashboard with a new asset ordering that is sortable. The market page has also been redesigned to be more streamlined. Hope you like it!
