### ISSUE TITLE
Issue in starting development server

### ISSUE THREAD

**Issue by ChanHongMing** [VenusProtocol/venus-protocol-interface#1811]
When I try to start the development server locally, I clone the repository and then run yarn and yarn start. The following happens.
![yarn](https://github.com/VenusProtocol/venus-protocol-interface/assets/91173675/1e59f28f-8702-4cbb-a598-fb90f0ab3ce1)
![yarn-start](https://github.com/VenusProtocol/venus-protocol-interface/assets/91173675/9df1a1c7-e497-4a6c-a4f6-ae3661c02cc9)
I am using windows 10. node v18.18.0 and npm 9.8.1 and yarn 1.22.21.
Something similar happens using docker-compose up as well
![docker-compose_up](https://github.com/VenusProtocol/venus-protocol-interface/assets/91173675/4281326d-bc87-4437-bb6a-c3e77a565d7e)
Seems to be related to lack of file in packages/contracts/generated/
Do I need to generate the contract myself and deploy on a local blockchain? I suppose I can just run it and it can get data just like [https://app.venus.io/#/](https://app.venus.io/#/) directly from the bsc public chain. 

Thanks a lot for any reply and guide.

**Comment by therealemjy** [comment]
Hi @ChanHongMing 
Could you try to run `yarn` again and see if this fixes the issue please?

To give you more context, you are right that the error is related to some files missing (as you pointed out, these are files that should be located at `src/packages/contracts/generated/`). These files are automatically generated after installing the project dependencies, through the `generate-contracts` script which itself is automatically executed through the `postinstall` script in the `package.json` file.
If the `yarn` command does not fix the issue, please run `yarn generate-contracts` and take a screenshot of your console logs so I can help further.

**Comment by ChanHongMing** [comment]
Seems the problem is ./src/packages/contracts/scripts/generateContractRecords/index.ts do not run properly
I just run yarn and the following show up
![yarn](https://github.com/VenusProtocol/venus-protocol-interface/assets/91173675/8f728462-98dc-4816-a608-569cba98a9cc)
and I run yarn generate-contracts
![yarngen-contract](https://github.com/VenusProtocol/venus-protocol-interface/assets/91173675/6ecbf3dc-f2b9-4141-ada3-4eb2b9fdb544)
I found out that windows interpret the ts file as video stream format and TV & movies pops up. And I changed the default app to vscode for .ts file. It don't work either. It only open the file without running it.
The console.log('Generating contracts...'); in line 6 of index.js didn't pops out in the terminal .
I found that there is a command ./src/packages/contracts/scripts/generateContractRecords/index.ts in generate-contracts scripts in package.json. I think there are some prerequisites for me to install or set up so that I can directly run the ts file this way.

**Comment by therealemjy** [comment]
I see. These files should be executed automatically using [tsx](https://www.npmjs.com/package/tsx). To be honest I'm not really sure why your environment is opening the files rather then executing them as scripts: perhaps there's a known issue with tsx and part of your setup. We haven't experienced this internally.
