### ISSUE TITLE
borrow error

### ISSUE THREAD

**Issue by talesbogoni** [VenusProtocol/venus-protocol-interface#254]
I have a problem with repayment.
On the main screen the borrow displays the value of 2.02.
When I click on the borrow, it shows the protocol balance 2.02, but when I go to make the payment, it only accepts 2.0 and with that I can't release the collateral.

**Comment by coreyar** [comment]
Hi @talesbogoni, happy to help troubleshoot this.
The total borrowed balance is displayed in dollars while the repayment is made in units of the borrowed asset. It is possible the discrepancy comes from here.
Are you able to repay the full amount by using the `Max` button?
