### ISSUE TITLE
Redirection issue with new Market page when switching Networks

### ISSUE THREAD

**Issue by Frayst2** [VenusProtocol/venus-protocol-interface#2836]
Hey,

There is a small issue with the new market UI page-> 

1) Go to the https://app.venus.io/#/core-pool/market/0xAeB0FEd69354f34831fe1D16475D9A83ddaCaDA6?chainId=42161
2) Switch to opBNB market
3) The UI will redirect to Dashboard page of BNBChain and not opBNB (selected network). --> issue

https://github.com/VenusProtocol/venus-protocol-interface/assets/173150773/0851acb3-f318-4b89-99f5-b192892fb470

**Comment by therealemjy** [comment]
Hi,
Thank you for bringing this to our attention. We'll have a look and get a fix for this issue very soon.

All the best.

**Comment by therealemjy** [comment]
This issue will be fixed in this [PR](https://github.com/VenusProtocol/venus-protocol-interface/pull/2839).

**Comment by Frayst2** [comment]
Perfect 👍 thank you!

**Comment by therealemjy** [comment]
This issue has now been fixed and deployed to the dApp.

Thank you for pointing our attention to this. If you find any other bug, do not hesitate to open a new GitHub issue.
