### ISSUE TITLE
Missing Supply / Borrow APY graphs for Ethereum, Arbitrum & opBNB

### ISSUE THREAD

**Issue by Frayst2** [VenusProtocol/venus-protocol-interface#3093]
Hey,

Could you please confirm if it is normal to not see the Supply / Borrow APY graphs in the new markets page for Ethereum, Arbitrum & opBNB networks?

I can see them only in BNB Chain network. Any plan to add them for these networks (backlog)?

Thanks,

<img width="730" alt="Screen" src="https://github.com/user-attachments/assets/16701dec-258c-46fc-b4f0-1263c390b2ad">

**Comment by therealemjy** [comment]
Hi @Frayst2 
Yes, that is expected for now. We are actually working on making the graphs available on all chains in [this PR](https://github.com/VenusProtocol/venus-protocol-interface/pull/3102).
Thanks

**Comment by Frayst2** [comment]
Perfect! Thanks 🙏
