### ISSUE TITLE
There is a big space between the header and title in Venus.io

### ISSUE THREAD

**Issue by Frayst2** [VenusProtocol/venus-protocol-interface#3260]
Hello,

When I connect to venus.io with my workstation (macbook 13p), I find that there is a very large space between the taskbar and the title  (Universal Money Markets) with the default browser resolution. I don't have the issue on mobile.

Is it possible to start the title of the page a bit higher cos it is look weird to scroll 5 times before to see the main content?

<img width="1440" alt="venus io" src="https://github.com/user-attachments/assets/0490fa58-50e9-4f66-8c41-5619793224f3">

**Comment by therealemjy** [comment]
Hello @Frayst2,
Thanks for your feedback. This is a choice taken by our design team, so we'll have to follow them on this one.
Thanks!
