### ISSUE TITLE
[New feature] Fix the header of tables

### ISSUE THREAD

**Issue by Frayst2** [VenusProtocol/venus-protocol-interface#3261]
Hello,

It is not a bug but more a new feature that could improve the user experience of Venus web app. Is it possible to keep the header bar of tables (fix) to always see the columns titles when the user scrolls down? ex: Dashboard, Core pool/IL views.

This feature is only necessary for workstation because it looks good on mobile with current Cards mechanism.

![UI-2](https://github.com/user-attachments/assets/191052cb-f3a9-4aaf-b505-faea909c0fa1)

**Comment by therealemjy** [comment]
Hi @Frayst2,
The UX you describe is ideal and something we actually explored a while ago. Unfortunately we were not able to implement it due to limitations.

The CSS way of making the header sticky is to apply `position: sticky` to it. Unfortunately this rule does not work when used inside a `table` tag.

Another possible way could be to make both the header and the table horizontally scrollable, then sync their scroll positions when either one is scrolled. However, with this approach we are forced to fix the widths of columns which could trim certain token values (for example if we had to show 154.00000000012 XVS).

That's the two approaches we tried to follow, without success. If you have any other idea or even better want to open a PR, I'd be happy to review!

**Comment by Frayst2** [comment]
Hello @therealemjy 
Thanks for your feedback and details. I got your point regarding the CSS limitation with table tag.

It could be interesting to review the List component from AAVE because it works pretty well on workstation and mobile with cards. I am not an expert but they use the  position: 'sticky' in ListHeaderWrapper.tsx. Nevertheless, I assume they created a custom version of table with ListItem and ListColumn.

https://github.com/aave/interface/tree/main/src/components/lists

From my point of view, we should trim some token values, it does not make sense to display 15 zero like:
- Daily XVS distribution 165.000000000000038 XVS
- VAI Vault  125.000000000000064

**Comment by therealemjy** [comment]
Aave's implementation also relies on fixed width columns unfortunately.

I get your point about trimming token values. I think it makes sense for most values, however if a token value is inferior to 1 then we'd be forced to show as many 0´s as necessary until we reach a non-zero decimal.
E.g.: 0.0000005 XVS
Perhaps a solution could be to display values that are small enough with an annotation like this one: < 0.00001 XVS
In which case we could also trim values superior to 1. What do you think?

**Comment by Frayst2** [comment]
I think the best option to display the trimming is the following:

![image](https://github.com/user-attachments/assets/c7d6d36a-233b-4b28-b23d-ca64331a4a42)

If the user places the cursor in the text, the full data is displayed.
Feasibility and complexity to be verified but it's pretty cool and works with all types of values. What do you think?

**Comment by therealemjy** [comment]
That's a nice option, definitely doable but would require a large amount of changes as every token value would now need to be displayed with a custom component, rather than using a simple string.

I'll add this to the todos and review with everyone. Thanks again for your feedback!

**Comment by Frayst2** [comment]
Welcome!

The idea is to create a custom component and maybe to use it firstly for the vault display (ex: VAI), then to use it for the daily XVS distribution panel, and to roll out for each tables.

After the trimming, the fix columns may be used in table component to enable the sticky header without risk ;) tbc. 

Good luck 👍

**Comment by therealemjy** [comment]
@Frayst2 we will be updating the rules for formatting values in this PR: https://github.com/VenusProtocol/venus-protocol-interface/pull/3297

Thanks again for your feedback.
