### ISSUE TITLE
The "Market size" referenced in Venus.io only contains the BNBchain network.

### ISSUE THREAD

**Issue by Frayst2** [VenusProtocol/venus-protocol-interface#3262]
Hello,

The current “Market size” & "Total Borrowed" displayed in Venus.io front end does not include all networks such as Ethereum, Arbitrum, opBNB, and zkSync. It is only BNBchain. It could be nice to include all markets with API call, as well as referencing the number of networks etc.

<img width="1236" alt="look" src="https://github.com/user-attachments/assets/1bbdeba5-979f-48a7-b1fb-06890247c56a">

Thanks,

**Comment by therealemjy** [comment]
Hi @Frayst2 
You're correct yes, this layout is out-of-date given we're now a multi chain dApp. We have it in our pipeline to do exactly what you described (show the total market size across all networks, show the amount of networks/assets), so you can expect the landing page to be updated in the coming weeks.

Thank you!
