### ISSUE TITLE
Security Vulnerability Report

### ISSUE THREAD

**Issue by 0xnare** [VenusProtocol/venus-protocol-interface#3379]
See the full details of the vulnerability in the following document link: [Vulnerability Report](https://docs.google.com/document/d/1XUscfVUv4lMG0L2Oh2nWEAIocLmUwoanrhfqeQkRD08/edit?usp=sharing)

**Comment by 0xnare** [comment]
Request access to the docs, and I will accept it ASAP. Alternatively, you can send me your email, and I will add you for access to the docs.

**Comment by 0xnare** [comment]
Hello @therealemjy , I have given you access. You will be able to view the docs. If you face any issues, let me know

**Comment by therealemjy** [comment]
Hi @0xnare ,
Thank you for opening this issue and giving me access to your document. I will review it and get back to you as soon as possible.
Thanks,
Maxime

**Comment by therealemjy** [comment]
Hi @0xnare 
I can confirm the validity of the vulnerability you highlighted to us. We have taken the necessary measures in consequence.

We'd like to reward you for letting us know, nonetheless with a high level of professionalism. Could you please give me an email address I can contact you on?

**Comment by therealemjy** [comment]
Great, I'll contact you through email and close this issue then.
