### ISSUE TITLE
Add a pin to historical rates card and add asset price bellow the asset

### ISSUE THREAD

**Issue by MichelDiz** [VenusProtocol/venus-protocol-interface#435]
A pin in historical rates card would help the usage, it is a bit boring to search for a specific asset informations. We set a main asset that we want to follow info. And everytime we refresh the page, we should se it there instead of SXP.

Asset price bellow the asset in all markets. That would make things fast to see. Instead of going to historical rates one by one to check the price from oracle.

**Comment by coreyar** [comment]
Thanks for the suggestion! I'll pass it along to the product team. In the meantime, you can sort the asset list to make it easier to find the asset you are looking for.
