### ISSUE TITLE
Cannot withdraw

### ISSUE THREAD

**Issue by peterblockman** [VenusProtocol/venus-protocol-interface#8]
Hi, I am trying to withdraw my asset from https://app.venus.io/dashboard, but It is showing `missing trie node` error 

![image](https://user-images.githubusercontent.com/37528158/134890441-cb73cc25-5b9d-4ef6-ab67-6bf56e18b55c.png)

Looks like something wrong with the provider.

**Comment by kkirka** [comment]
@peterblockman is the issue still reproducible?

**Comment by coreyar** [comment]
We have refactored and redesigned this interface. I'm going to close this issue because it is inactive and any issues should be resolved with the new interface.
